# Generated by Django 3.1.1 on 2020-10-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Advisor', 'Advisor'), ('Investor', 'Investor'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
